services:
  web:
    build: .
    image: ureg_web
    container_name: web
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app