services:
  web:
    build:
      args:
        user: ureg
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: ureg_web
    container_name: web
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app